var champs = {
_0: { NAME: 'All', TYPE:[] },
_1: { NAME: 'Annie', TYPE:['ranged','recommended','mage'] },
_2: { NAME: 'Olaf', TYPE:['fighter','melee'] },
_3: { NAME: 'Galio', TYPE:['support','tank','melee'] },
_4: { NAME: 'Twisted Fate', TYPE:['pusher','assassin','ranged'] },
_5: { NAME: 'Xin Zhao', TYPE:['assassin','fighter','melee'] },
_6: { NAME: 'Urgot', TYPE:['ranged','fighter'] },
_7: { NAME: 'LeBlanc', TYPE:['assassin','ranged','mage'] },
_8: { NAME: 'Vladimir', TYPE:['ranged','mage','fighter'] },
_9: { NAME: 'Fiddlesticks', TYPE:['jungler','ranged','mage'] },
_10: { NAME: 'Kayle', TYPE:['support','fighter'] },
_11: { NAME: 'Master Yi', TYPE:['recommended','carry','melee'] },
_12: { NAME: 'Alistar', TYPE:['pusher','tank','melee'] },
_13: { NAME: 'Ryze', TYPE:['ranged','recommended','mage'] },
_14: { NAME: 'Sion', TYPE:['fighter','melee'] },
_15: { NAME: 'Sivir', TYPE:['pusher','ranged','recommended','carry'] },
_16: { NAME: 'Soraka', TYPE:['support','ranged','recommended'] },
_17: { NAME: 'Teemo', TYPE:['support','ranged','stealth'] },
_18: { NAME: 'Tristana', TYPE:['ranged','recommended','carry'] },
_19: { NAME: 'Warwick', TYPE:['jungler','recommended','fighter','melee'] },
_20: { NAME: 'Nunu', TYPE:['jungler','recommended','fighter','melee'] },
_21: { NAME: 'Miss Fortune', TYPE:['ranged','carry'] },
_22: { NAME: 'Ashe', TYPE:['ranged','recommended','carry'] },
_23: { NAME: 'Tryndamere', TYPE:['carry','melee'] },
_24: { NAME: 'Jax', TYPE:['fighter','melee'] },
_25: { NAME: 'Morgana', TYPE:['support','ranged','mage'] },
_26: { NAME: 'Zilean', TYPE:['support','ranged','mage'] },
_27: { NAME: 'Singed', TYPE:['fighter','melee'] },
_28: { NAME: 'Evelynn', TYPE:['assassin','stealth','melee'] },
_29: { NAME: 'Twitch', TYPE:['ranged','stealth','carry'] },
_30: { NAME: 'Karthus', TYPE:['ranged','mage'] },
_31: { NAME: 'Cho`Gath', TYPE:['mage','fighter','melee'] },
_32: { NAME: 'Amumu', TYPE:['tank','melee'] },
_33: { NAME: 'Rammus', TYPE:['recommended','tank','melee'] },
_34: { NAME: 'Anivia', TYPE:['ranged','mage'] },
_35: { NAME: 'Shaco', TYPE:['assassin','stealth','melee'] },
_36: { NAME: 'Dr. Mundo', TYPE:['fighter','melee'] },
_37: { NAME: 'Sona', TYPE:['support','ranged','recommended'] },
_38: { NAME: 'Kassadin', TYPE:['assassin','mage','melee'] },
_39: { NAME: 'Irelia', TYPE:['assassin','melee'] },
_40: { NAME: 'Janna', TYPE:['support','ranged'] },
_41: { NAME: 'Gangplank', TYPE:['carry','melee'] },
_42: { NAME: 'Corki', TYPE:['ranged','carry'] },
_43: { NAME: 'Karma', TYPE:['support','ranged'] },
_44: { NAME: 'Taric', TYPE:['support','recommended','tank','melee'] },
_45: { NAME: 'Veigar', TYPE:['ranged','mage'] },
_48: { NAME: 'Trundle', TYPE:['fighter','melee'] },
_50: { NAME: 'Swain', TYPE:['ranged','mage'] },
_51: { NAME: 'Caitlyn', TYPE:['ranged','carry'] },
_53: { NAME: 'Blitzcrank', TYPE:['fighter','melee'] },
_54: { NAME: 'Malphite', TYPE:['fighter','melee'] },
_55: { NAME: 'Katarina', TYPE:['assassin','recommended','melee'] },
_56: { NAME: 'Nocturne', TYPE:['assassin','melee'] },
_57: { NAME: 'Maokai', TYPE:['pusher','tank','melee'] },
_58: { NAME: 'Renekton', TYPE:['fighter','melee'] },
_59: { NAME: 'Jarvan IV', TYPE:['fighter','melee'] },
_61: { NAME: 'Orianna', TYPE:['ranged','mage'] },
_62: { NAME: 'WuKong', TYPE:['stealth','fighter','melee'] },
_63: { NAME: 'Brand', TYPE:['ranged','mage'] },
_64: { NAME: 'Lee Sin', TYPE:['assassin','melee'] },
_67: { NAME: 'Vayne', TYPE:['assassin','stealth','ranged','carry'] },
_68: { NAME: 'Rumble', TYPE:['pusher','mage','melee'] },
_69: { NAME: 'Cassiopeia', TYPE:['ranged','mage'] },
_72: { NAME: 'Skarner', TYPE:['jungler','fighter','melee'] },
_74: { NAME: 'Heimerdinger', TYPE:['pusher','ranged','mage'] },
_75: { NAME: 'Nasus', TYPE:['pusher','recommended','fighter','melee'] },
_76: { NAME: 'Nidalee', TYPE:['pusher','support'] },
_77: { NAME: 'Udyr', TYPE:['fighter','melee'] },
_78: { NAME: 'Poppy', TYPE:['assassin','fighter','melee'] },
_79: { NAME: 'Gragas', TYPE:['fighter','melee'] },
_80: { NAME: 'Pantheon', TYPE:['assassin','melee'] },
_81: { NAME: 'Ezreal', TYPE:['ranged','carry'] },
_82: { NAME: 'Mordekaiser', TYPE:['pusher','fighter','melee'] },
_83: { NAME: 'Yorick', TYPE:['pusher','fighter','melee'] },
_84: { NAME: 'Akali', TYPE:['assassin','stealth','melee'] },
_85: { NAME: 'Kennen', TYPE:['ranged','mage'] },
_86: { NAME: 'Garen', TYPE:['recommended','fighter','melee'] },
_89: { NAME: 'Leona', TYPE:['tank','melee'] },
_90: { NAME: 'Malzahar', TYPE:['ranged','mage'] },
_91: { NAME: 'Talon', TYPE:['assassin','melee'] },
_92: { NAME: 'Riven', TYPE:['fighter','melee'] },
_96: { NAME: 'Kog`Maw', TYPE:['ranged','carry'] },
_98: { NAME: 'Shen', TYPE:['support','tank','melee'] },
_99: { NAME: 'Lux', TYPE:['support','ranged','mage'] },
_101: { NAME: 'Xerath', TYPE:['ranged','mage'] },
_102: { NAME: 'Shyvana', TYPE:['fighter','melee'] },
_103: { NAME: 'Ahri', TYPE:['assassin','ranged','mage'] },
_104: { NAME: 'Graves', TYPE:['ranged','carry'] },
_105: { NAME: 'Fizz', TYPE:['assassin','fighter','melee'] },
_106: { NAME: 'Volibear', TYPE:['jungler','fighter','tank','melee'] },
_107: { NAME: 'Rengar', TYPE:['fighter', 'jungler', 'melee', 'stealth'] },
_110: { NAME: 'Varus', TYPE:['carry','ranged'] },
_111: { NAME: 'Nautilus', TYPE:['mage','ranged','pusher'] },
_112: { NAME: 'Viktor', TYPE:['melee','fighter'] },
_113: { NAME: 'Sejuani', TYPE:['melee','tank','jungler'] },
_114: { NAME: '피오라', TYPE:['melee','carry'] },
_115: { NAME: 'Ziggs', TYPE:['mage','ranged','pusher'] },
_117: { NAME: '룰루', TYPE:['support','ranged'] },
_120: { NAME: '헤카림', TYPE:['fighter','jungler','melee'] },
_121: { NAME: '카직스', TYPE:['assassin','melee'] },
_122: { NAME: '다리우스', TYPE:['fighter','melee'] },
_119: { NAME: '드레이븐', TYPE:['fighter','melee'] },
_126: { NAME: '제이스', TYPE:['fighter','melee'] },
_131: { NAME: 'Diana', TYPE:['fighter','melee','jungler','mage'] },
_134: { NAME: '신드라', TYPE:['ranged','mage'] },
_60: { NAME: 'Elise', TYPE:['jungler','ranged','mage'] },
_143: { NAME: 'Zyra', TYPE:['mage','ranged'] },
_238: { NAME: '제드', TYPE:['assassin','melee'] },
_254: { NAME: 'Vi', TYPE:['assassin','melee'] },
_267: { NAME: 'Nami', TYPE:['assassin','melee'] },
_412: { NAME: '쓰레쉬', TYPE:[] },
_133: { NAME: '퀸', TYPE:[] }
};
function champtypename(type)
{
        var tn = {
        'assassin' : '암살형',
        'melee' : '<B>근접</B>',
        'carry' : '주딜러',
        'support' : '서포터',
        'ranged' : '<B>원거리</B>',
        'fighter' : '전사',
        'mage' : '마법사',
        'stealth' : '은신',
        'jungler' : '정글러',
        'tank' : '탱커'
        };

        return tn[type] ? tn[type] : type;
}
